apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: calculator
  template:
    metadata:
      labels:
        app: calculator
    spec:
      containers:
      - name: calculator
        image: pial847/calculator-app:1.0.0
        ports:
        - containerPort: 5000
